services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - 3000:3000
        image: frontend:docu-ai

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - 8008:8008
        env_file:
            - ./backend/.env

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - 6379:63790

    postgreSQL:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        env_file:
            - ./backend/.env.postgres
        volumes:
            - postgres-vl:/var/lib/postgresql/data

    minIO:
        image: minio/minio
        container_name: minio
        ports:
            - 9000:9000
            - 9090:9090
        environment:
            - MINIO_CONFIG_ENV_FILE=/etc/config.env
        volumes:
            - ./backend/uploads/:/mnt/data
            - ./backend/minio/config.env:/etc/config.env
        command: server --console-address ":9090"

    pgadmin:
        image: dpage/pgadmin4:9.8.0
        container_name: pgadmin
        ports:
            - 80:80
        env_file:
            - ./backend/.env.postgres
        volumes:
            - postgres-admin-vl:/var/lib/postgresql/data

volumes:
    postgres-vl:
        name: pdata
    postgres-admin-vl:
        name: pgdata